---
# Maintain project dependencies
version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: ".github/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    commit-message:
      prefix: "[github-actions]"
    groups:
      actions:
        patterns:
          - "*"